name: Bug Report
description: Something isn't working the way you expect
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "@claude"

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Describe what went wrong.
      placeholder: "e.g. When I click the Edit button, the text disappears and I can't type anything"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      placeholder: "e.g. I expected to see the existing text in an editable field"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we make it happen again?
      placeholder: |
        1. Open the app
        2. Add a task
        3. Click Edit
        4. See the bug
    validations:
      required: false

  - type: dropdown
    id: frequency
    attributes:
      label: Does it happen every time?
      options:
        - Every time
        - Sometimes
        - Only happened once
    validations:
      required: false
