name: Bug Report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this! Fill in as much as you can — the more detail you give, the faster it gets fixed.

        > **Note**: Submitting this form automatically notifies our AI contributor, which will ask any clarifying questions it needs.

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Describe the problem clearly. What went wrong?
      placeholder: e.g. When I click the "Save" button, nothing happens and I see a spinning loader forever.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: What should have happened instead?
      placeholder: e.g. The form should save and show a success message.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we make it happen again? Step-by-step if possible.
      placeholder: |
        1. Go to the settings page
        2. Click "Save"
        3. See the spinner
    validations:
      required: false

  - type: dropdown
    id: frequency
    attributes:
      label: Does this happen every time?
      options:
        - "Yes, every time"
        - "Most of the time"
        - "Sometimes"
        - "Only happened once"
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Anything else?
      description: Screenshots, error messages, browser, device — anything that might help.
    validations:
      required: false

  - type: markdown
    attributes:
      value: "@claude"
